import os
import json
import sys
from tree_sitter import Parser, Language
import tree_sitter_c as tsc
import tiktoken
from typing import Dict, List, Set, Optional, Any,Tuple
from dataclasses import dataclass, field
from collections import defaultdict

# Increase Python's recursion limit
sys.setrecursionlimit(3000)

@dataclass
class Config:
    MAX_TOKENS: int = 2000
    TRAVERSE_DEPTH: int = 2

@dataclass
class CodeNode:
    id: int
    text: str
    type: str
    children_types: List[str]
    origin_file: Optional[str] = None
    parent_id: Optional[int] = None
    parent_type: Optional[str] = None
    relationships: Dict[str, List[int]] = field(default_factory=lambda: {
        'calls': [],           # Function calls
        'called_by': [],       # Functions that call this
        # 'uses_struct': [],     # Structs used by this node
        # 'used_by_struct': [],  # Structs that use this node
        # 'includes': [],        # Files included by this
        # 'included_by': [],     # Files that include this
        # 'defines_macro': [],   # Macros defined here
        # 'uses_macro': [],      # Macros used here
        # 'defines_var': [],     # Variables defined here
        # 'uses_var': [],        # Variables used here
        # 'defines_type': [],    # Types defined here
        # 'uses_type': []        # Types used here
    })
    chunks: Optional[List['CodeNode']] = None
    @staticmethod
    def from_node(node: Any, node_id: int, parent_id: Optional[int] = None, 
                 file: Optional[str] = None, relationships: Optional[Dict[str, List[int]]] = None) -> 'CodeNode':
        return CodeNode(
            id=node_id,
            text=node.text.decode('utf-8'),
            type=node.type,
            children_types=[child.type for child in node.children],
            parent_id=parent_id,
            origin_file=file,
            parent_type=node.parent.type if node.parent else None,
            relationships=relationships or {'calls': [], 'called_by': []}
        )

    @staticmethod
    def from_group(nodes: List['CodeNode'], node_id: int, group_type: str = 'group', 
                  parent_id: Optional[int] = None, file: Optional[str] = None,
                  relationships: Optional[Dict[str, List[int]]] = None) -> 'CodeNode':
        texts = []
        children_types = []
        
        for node in nodes:
            texts.append(node.text)
            children_types.extend(node.children_types)
            
        return CodeNode(
            id=node_id,
            text='\n'.join(texts),
            type=group_type,
            children_types=children_types,
            parent_id=parent_id,
            origin_file=file,
            relationships=relationships or {'calls': [], 'called_by': []}
        )

@dataclass
class ParseContext:
    function_definitions: Dict[str, int] = field(default_factory=dict)
    relationships: Dict[int, Dict[str, List[int]]] = field(default_factory=dict)
    file_functions: Dict[str, List[str]] = field(default_factory=lambda: defaultdict(list))

class TokenHandler:
    def __init__(self):
        self.tokenizer = tiktoken.get_encoding("cl100k_base")
    
    def count_tokens(self, text: str) -> int:
        return len(self.tokenizer.encode(text))

@dataclass
class IdRange:
    current: int = 0
    step: int = 1

class NodeIdGenerator:
    def __init__(self):
        self._current_id = 0
        self._used_ids = set()  # Track all generated IDs
        
    def get_id(self, node: Any) -> int:
        """
        Generate a unique ID for a node.
        Using node as parameter to maintain compatibility, though we don't use it.
        """
        self._current_id += 1
        self._used_ids.add(self._current_id)
        return self._current_id
    
    def is_valid_id(self, id_to_check: int) -> bool:
        """Check if an ID has been generated by this generator"""
        return id_to_check in self._used_ids
    
class RelationshipValidator:
    def __init__(self, id_generator: NodeIdGenerator):
        self.id_generator = id_generator
        self._relationship_map = defaultdict(set)  # Track all relationships
        
    def register_relationship(self, source_id: int, target_id: int, rel_type: str) -> None:
        """Register a relationship between two nodes"""
        self._relationship_map[rel_type].add((source_id, target_id))
    
    def validate_relationships(self, nodes: List[CodeNode]) -> Tuple[List[Dict], List[Dict]]:
        """
        Validate all relationships in the nodes
        Returns lists of invalid and fixed relationships
        """
        valid_ids = {node.id for node in nodes}
        invalid_rels = []
        fixed_rels = []
        
        for node in nodes:
            for rel_type, rel_ids in node.relationships.items():
                # Skip empty relationships
                if not rel_ids:
                    continue
                    
                # Create new list for valid IDs
                valid_rel_ids = []
                
                for rel_id in rel_ids:
                    if rel_id not in valid_ids:
                        # Record invalid relationship
                        invalid_rels.append({
                            'node_id': node.id,
                            'relationship_type': rel_type,
                            'invalid_id': rel_id
                        })
                    else:
                        valid_rel_ids.append(rel_id)
                
                if len(valid_rel_ids) != len(rel_ids):
                    # Record fixed relationship
                    fixed_rels.append({
                        'node_id': node.id,
                        'relationship_type': rel_type,
                        'old_ids': rel_ids,
                        'new_ids': valid_rel_ids
                    })
                    # Update the relationship with only valid IDs
                    node.relationships[rel_type] = valid_rel_ids
        
        return invalid_rels, fixed_rels

    def fix_bidirectional_relationships(self, nodes: List[CodeNode]) -> List[Dict]:
        """
        Ensure bidirectional relationships are consistent
        Returns list of fixed relationships
        """
        fixes = []
        id_to_node = {node.id: node for node in nodes}
        
        # Define bidirectional relationship pairs
        bidirectional_pairs = {
            'calls': 'called_by',
        }
        
        for node in nodes:
            for rel_type, inverse_type in bidirectional_pairs.items():
                if rel_type in node.relationships:
                    for target_id in node.relationships[rel_type]:
                        if target_id in id_to_node:
                            target_node = id_to_node[target_id]
                            # Ensure inverse relationship exists
                            if node.id not in target_node.relationships.get(inverse_type, []):
                                if inverse_type not in target_node.relationships:
                                    target_node.relationships[inverse_type] = []
                                target_node.relationships[inverse_type].append(node.id)
                                fixes.append({
                                    'node_id': target_id,
                                    'relationship_type': inverse_type,
                                    'added_id': node.id
                                })
        
        return fixes
def read_file_content(filepath: str) -> str:
    encodings = ['utf-8', 'utf-8-sig', 'latin-1', 'cp1252']
    errors = []
    
    for encoding in encodings:
        try:
            with open(filepath, 'r', encoding=encoding) as file:
                content = file.read()
                # Validate content is readable
                content.encode('utf-8')
                return content
        except UnicodeDecodeError as e:
            errors.append(f"{encoding}: {str(e)}")
        except UnicodeEncodeError as e:
            errors.append(f"{encoding}: {str(e)}")
        except Exception as e:
            errors.append(f"{encoding}: Unexpected error: {str(e)}")
            
    error_msg = f"Unable to read {filepath} with any of the attempted encodings:\n"
    error_msg += "\n".join(errors)
    raise UnicodeDecodeError(error_msg)

class CParser:
    MINIMUM_CHUNK_TOKENS = 50  # Minimum tokens for a standalone chunk
    
    MERGEABLE_TYPES = {
        'declaration',
        'expression_statement',
        'null_statement',
        'labeled_statement',
        'preproc_def',
        'preproc_include',
        'assignment_expression',
        'call_expression',
        'enumerator',
        'field_declaration'
    }
    
    STANDALONE_TYPES = {
        'if_statement',
        'while_statement',
        'for_statement',
        'switch_statement',
    }
    
    def __init__(self, config: Optional[Config] = None):
        self.config = config or Config()
        self.parser = self._setup_parser()
        self.token_handler = TokenHandler()
        self.id_generator = NodeIdGenerator()
        self.processed_nodes = []
        self.context = ParseContext()
        self.current_filename = None
        self.current_preprocessor_group = []
        self.current_scope_stack: List[str] = []  # Track current scope for variable resolution
        self.node_id_map = {}  # Add this to track node IDs
        self.definition_nodes = {}  # Store actual nodes for definitions

        self.relationship_validator = RelationshipValidator(self.id_generator)
        self.processed_nodes = []
        self.context = ParseContext()
    @staticmethod
    def _setup_parser() -> Parser:
        C_LANGUAGE = Language(tsc.language())
        parser = Parser(C_LANGUAGE)
        return parser

    def get_node_id(self, node: Any) -> int:
        """Get a consistent ID for a node"""
        if isinstance(node, str):
            return self.id_generator.get_id(node)
        
        node_address = id(node)
        if node_address not in self.node_id_map:
            self.node_id_map[node_address] = self.id_generator.get_id(node.type)
            # Store the node itself if it's a definition
            if node.type in ["function_definition", "struct_specifier", "preproc_def", "declaration"]:
                self.definition_nodes[self.node_id_map[node_address]] = node
                
        return self.node_id_map[node_address]

    def create_element_info(self, node: Any, file: str) -> CodeNode:
        node_id = self.get_node_id(node)
        relationships = {
            'calls': [], 'called_by': [],
        }
        return CodeNode.from_node(
            node=node,
            node_id=node_id,
            file=file,
            relationships=relationships
        )
    
    def should_merge_statements(self, node1: CodeNode, node2: CodeNode) -> bool:
        if node1.type in self.STANDALONE_TYPES or node2.type in self.STANDALONE_TYPES:
            return False
                
        if node1.type == 'preproc_def' and node2.type == 'preproc_def':
            return True
                
        simple_types = {'expression_statement', 'declaration', 'call_expression'}
        is_simple_1 = node1.type in simple_types
        is_simple_2 = node2.type in simple_types
        
        if is_simple_1 and is_simple_2:
            combined_text = node1.text + '\n' + node2.text
            combined_tokens = self.token_handler.count_tokens(combined_text)
            return combined_tokens <= self.MINIMUM_CHUNK_TOKENS
                
        return False

    def flush_group(self, current_group: List[CodeNode]) -> None:
        if not current_group:
            return
                
        if len(current_group) > 1:
            group_id = self.get_node_id("merged_statements")
            group_relationships = {
                'calls': [], 'called_by': [],
            }
            
            for node in current_group:
                if node.relationships:
                    for rel_type, rel_ids in node.relationships.items():
                        group_relationships[rel_type].extend(rel_ids)
            
            for rel_type in group_relationships:
                group_relationships[rel_type] = list(set(group_relationships[rel_type]))
            
            merged_node = CodeNode.from_group(
                nodes=current_group,
                node_id=group_id,
                group_type='merged_statements',
                parent_id=current_group[0].parent_id,
                file=self.current_filename,
                relationships=group_relationships
            )
            self.processed_nodes.append(merged_node)
        else:
            self.processed_nodes.append(current_group[0])


    def find_function_calls_in_chunk(self, node: Any) -> List[str]:
        calls = []
        stack = [(node, [])]
        
        while stack:
            current_node, _ = stack.pop()
            
            if current_node.type == 'call_expression':
                func_identifier = current_node.child_by_field_name('function')
                if func_identifier:
                    if func_identifier.type == 'identifier':
                        func_name = func_identifier.text.decode('utf-8').strip()
                        calls.append(func_name)
                    elif func_identifier.type == 'field_expression':
                        field_name = func_identifier.child_by_field_name('field')
                        if field_name:
                            func_name = field_name.text.decode('utf-8').strip()
                            calls.append(func_name)
                    elif func_identifier.type == 'pointer_expression':
                        field_name = func_identifier.child_by_field_name('field')
                        if field_name:
                            func_name = field_name.text.decode('utf-8').strip()
                            calls.append(func_name)
            
            for child in current_node.children:
                stack.append((child, []))
                
        return calls

    def update_node_relationships(self, node_id: int, relationships_update: Dict[str, List[int]]) -> None:
        """Updated version with relationship tracking"""
        if node_id not in self.context.relationships:
            self.context.relationships[node_id] = {
                'calls': [], 'called_by': [],
            }
        
        for rel_type, rel_ids in relationships_update.items():
            # Filter out invalid IDs
            valid_ids = [rel_id for rel_id in rel_ids 
                        if self.id_generator.is_valid_id(rel_id) and rel_id != node_id]
            
            if rel_type in self.context.relationships[node_id]:
                # Add new valid IDs
                self.context.relationships[node_id][rel_type].extend(valid_ids)
                # Remove duplicates while preserving order
                self.context.relationships[node_id][rel_type] = list(dict.fromkeys(
                    self.context.relationships[node_id][rel_type]
                ))
                
                # Update inverse relationship (calls -> called_by)
                if rel_type == 'calls':
                    for target_id in valid_ids:
                        if target_id not in self.context.relationships:
                            self.context.relationships[target_id] = {
                                'calls': [], 
                                'called_by': []
                            }
                        if node_id not in self.context.relationships[target_id]['called_by']:
                            self.context.relationships[target_id]['called_by'].append(node_id)
    
    def get_chunk_relationships(self, node: Any, chunk_id: int) -> Dict[str, List[int]]:
        """Get all relationships with consistent IDs"""
        relationships = {
            'calls': [], 'called_by': [],
        }

        # Get node ID for the current node
        node_id = self.get_node_id(node)

        # Function calls
        calls = self.find_function_calls_in_chunk(node)
        for func_name in calls:
            if func_name in self.context.function_definitions:
                callee_id = self.context.function_definitions[func_name]
                if self.id_generator.is_valid_id(callee_id):  # Verify ID is valid
                    relationships['calls'].append(callee_id)

        # Ensure all relationship lists contain unique IDs
        for rel_type in relationships:
            relationships[rel_type] = list(set(relationships[rel_type]))

        return relationships
    
    def _process_single_node(self, node: Any) -> Optional[CodeNode]:
        """Process a single node with enhanced relationship tracking"""
        try:
            parent_id = id(node.parent) if node.parent else None
            node_id = self.get_node_id(node)
            
            # Create basic node info
            if node.type == "function_definition":
                element = self.create_element_info(node, self.current_filename)
                # Store the node ID for this function
                declarator = node.child_by_field_name('declarator')
                if declarator:
                    identifier = None
                    declarator_stack = [declarator]
                    while declarator_stack:
                        current = declarator_stack.pop()
                        if current.type == 'identifier':
                            identifier = current
                            break
                        for child in current.children:
                            declarator_stack.append(child)
                    if identifier:
                        func_name = identifier.text.decode('utf-8').strip()
                        # Store the actual node ID
                        self.context.function_definitions[func_name] = node_id
                        print(f"Processing function {func_name} with ID {node_id}")
            elif node.type == "preproc_include":
                element = self.create_element_info(node, self.current_filename)
            elif node.type == "preproc_def":
                element = self.create_element_info(node, self.current_filename)
                element.parent_id = parent_id
            elif node.type in ["preproc_if", "preproc_ifdef", "preproc_ifndef"]:
                element = self.create_element_info(node, self.current_filename)
            elif node.type == "struct_specifier":
                element = self.create_element_info(node, self.current_filename)
            elif node.type == "enum_specifier":
                element = self.create_element_info(node, self.current_filename)
            else:
                return None

            # Initialize relationships
            relationships_update = {}
            
            # Track function calls
            if node.type in ['function_definition', 'call_expression']:
                calls = self.find_function_calls_in_chunk(node)
                called_ids = [self.context.function_definitions[f] for f in calls 
                            if f in self.context.function_definitions]
                relationships_update['calls'] = called_ids
            
            # Update all relationships
            self.update_node_relationships(node_id, relationships_update)
            element.relationships = self.context.relationships[node_id]
            
            return element
            
        except Exception as e:
            print(f"Error processing node of type {node.type}: {str(e)}")
            return None
    def _cleanup_file_context(self):
        """Clean up context data for current file"""
        if self.current_filename in self.context.file_functions:
            old_functions = self.context.file_functions[self.current_filename]
            for func_name in old_functions:
                if func_name in self.context.function_definitions:
                    func_id = self.context.function_definitions[func_name]
                    if func_id in self.context.relationships:
                        del self.context.relationships[func_id]
                    del self.context.function_definitions[func_name]

    def _collect_definitions(self, node: Any):
        """Collect all definitions (functions, structs, macros, etc.)"""
        stack = [(node, 0)]
        
        while stack:
            current_node, depth = stack.pop()
            node_id = self.get_node_id(current_node)  # Get consistent ID
             # Collect function definitions
            if current_node.type == "function_definition":
                declarator = current_node.child_by_field_name('declarator')
                if declarator:
                    identifier = self._find_identifier(declarator)
                    if identifier:
                        func_name = identifier.text.decode('utf-8').strip()
                        self.context.function_definitions[func_name] = node_id
                        print(f"Registered function {func_name} with ID {node_id}")

            for child in current_node.children:
                stack.append((child, depth + 1))
                                
    def _find_identifier(self, node: Any) -> Optional[Any]:
        """Helper function to find identifier nodes"""
        if node.type == 'identifier':
            return node
        
        for child in node.children:
            result = self._find_identifier(child)
            if result:
                return result
        return None

    def process_node_iterative(self, root_node: Any) -> None:
        """Process nodes iteratively with improved statement merging"""
        stack = [(root_node, 0)]
        current_group = []  # Group for collecting consecutive small statements
        
        while stack:
            node, depth = stack.pop()
            
            if depth >= self.config.TRAVERSE_DEPTH:
                continue

            # Process current node
            element_info = self._process_single_node(node)
            if element_info:
                # Check if we should start a new group
                if current_group:
                    should_merge = (
                        self.should_merge_statements(current_group[-1], element_info) and
                        current_group[-1].parent_id == element_info.parent_id
                    )
                    if not should_merge:
                        self.flush_group(current_group)
                        current_group = []
                
                # Add current node to group
                current_group.append(element_info)
                
                # Initialize relationships if needed
                if element_info.id not in self.context.relationships:
                    self.context.relationships[element_info.id] = {
                        'calls': [], 'called_by': [],
                    }

                # Process chunks if needed (for larger nodes)
                chunks = self.chunk_code(element_info)
                if chunks:
                    element_info.chunks = chunks

            # Add children to stack in reverse order
            for child in reversed(node.children):
                if child.type != "comment":
                    stack.append((child, depth + 1))
        
        # Flush any remaining group
        if current_group:
            self.flush_group(current_group)
    def chunk_code(self, element: CodeNode) -> Optional[List[CodeNode]]:
        """Split large code nodes into smaller chunks while maintaining relationships"""
        code = element.text
        if not code.strip():
            return None
            
        total_tokens = self.token_handler.count_tokens(code)
        if total_tokens <= self.config.MAX_TOKENS:
            return None

        tree = self.parser.parse(bytes(code, "utf8"))
        root_node = tree.root_node
        chunks: List[CodeNode] = []
        parent_id = element.id
        file = element.origin_file

        def get_mergeable_group(nodes: List[Any], start_idx: int) -> List[Any]:
            if start_idx >= len(nodes):
                return []
                
            first_node = nodes[start_idx]
            group = [first_node]
            current_idx = start_idx + 1
            
            if first_node.type == 'preproc_def':
                while (current_idx < len(nodes) and 
                       nodes[current_idx].type == 'preproc_def'):
                    group.append(nodes[current_idx])
                    current_idx += 1
            else:
                while (current_idx < len(nodes) and 
                       nodes[current_idx].type in self.MERGEABLE_TYPES):
                    group.append(nodes[current_idx])
                    current_idx += 1
                    
            return group

        def process_nodes_iterative(root: Any) -> None:
            stack = [(root, [])]
            
            while stack:
                node, path = stack.pop()
                
                if not node.children:
                    if node.type != "comment":
                        chunk_id = self.get_node_id(node)
                        relationships = self.get_chunk_relationships(node, chunk_id)
                        chunk_node = CodeNode.from_node(
                            node=node,
                            node_id=chunk_id,
                            parent_id=parent_id,
                            file=file,
                            relationships=relationships
                        )
                        if self.token_handler.count_tokens(chunk_node.text) <= self.config.MAX_TOKENS:
                            chunks.append(chunk_node)
                            self.context.relationships[chunk_id] = relationships
                    continue

                children = [child for child in node.children if child.type != "comment"]
                if not children:
                    continue

                idx = 0
                while idx < len(children):
                    child = children[idx]
                    
                    if child.type in self.MERGEABLE_TYPES:
                        group = get_mergeable_group(children, idx)
                        if group:
                            chunk_id = self.get_node_id(node)
                            group_relationships = {
                                'calls': [], 'called_by': [],
                            }
                            grouped_chunks = []
                            
                            for n in group:
                                sub_chunk_id = self.get_node_id(n)
                                sub_relationships = self.get_chunk_relationships(n, sub_chunk_id)
                                group_relationships['calls'].extend(sub_relationships['calls'])
                                chunk_node = CodeNode.from_node(
                                    node=n,
                                    node_id=sub_chunk_id,
                                    parent_id=chunk_id,
                                    file=file,
                                    relationships=sub_relationships
                                )
                                grouped_chunks.append(chunk_node)
                                self.context.relationships[sub_chunk_id] = sub_relationships
                            
                            group_relationships['calls'] = list(set(group_relationships['calls']))
                            
                            chunk_node = CodeNode.from_group(
                                nodes=grouped_chunks,
                                node_id=chunk_id,
                                group_type='merged_statements',
                                parent_id=parent_id,
                                file=file,
                                relationships=group_relationships
                            )
                            
                            if self.token_handler.count_tokens(chunk_node.text) <= self.config.MAX_TOKENS:
                                chunks.append(chunk_node)
                                self.context.relationships[chunk_id] = group_relationships
                            else:
                                chunks.extend(grouped_chunks)
                            
                            idx += len(group)
                            continue
                    
                    if child.type not in self.STANDALONE_TYPES:
                        chunk_id = self.get_node_id(child)
                        relationships = self.get_chunk_relationships(child, chunk_id)
                        chunk_node = CodeNode.from_node(
                            node=child,
                            node_id=chunk_id,
                            parent_id=parent_id,
                            file=file,
                            relationships=relationships
                        )
                        if self.token_handler.count_tokens(chunk_node.text) <= self.config.MAX_TOKENS:
                            chunks.append(chunk_node)
                            self.context.relationships[chunk_id] = relationships
                        else:
                            stack.append((child, path + [node.type]))
                    
                    idx += 1

        process_nodes_iterative(root_node)
        
        if len(chunks) < 2:
            return None
        
        return chunks
        
    def process_file(self, filepath: str) -> List[CodeNode]:
        try:
            content = read_file_content(filepath)
        except Exception as e:
            print(f"Error reading {filepath}: {str(e)}")
            return []

        self.current_filename = os.path.basename(filepath)
        self.current_preprocessor_group = []  # Reset preprocessor group
        
        try:
            tree = self.parser.parse(bytes(content, "utf8"))
            root_node = tree.root_node

            # Clean up old file data
            if self.current_filename in self.context.file_functions:
                self._cleanup_file_context()

            # Reset file tracking
            self.context.file_functions[self.current_filename] = []
            self.processed_nodes = []  # Reset processed nodes
            
            # First pass: collect all definitions
            self._collect_definitions(root_node)
            
            # Second pass: process nodes and build relationships
            self.process_node_iterative(root_node)

            # After processing nodes, validate relationships
            invalid_rels, fixed_rels = self.relationship_validator.validate_relationships(self.processed_nodes)
            if invalid_rels:
                print(f"Found {len(invalid_rels)} invalid relationships")
                print("Sample of invalid relationships:", invalid_rels[:5])
                
            if fixed_rels:
                print(f"Fixed {len(fixed_rels)} relationships")
                print("Sample of fixed relationships:", fixed_rels[:5])
            
            # Fix bidirectional relationships
            bidirectional_fixes = self.relationship_validator.fix_bidirectional_relationships(self.processed_nodes)
            if bidirectional_fixes:
                print(f"Fixed {len(bidirectional_fixes)} bidirectional relationships")
                print("Sample of bidirectional fixes:", bidirectional_fixes[:5])

            return self.processed_nodes

        except Exception as e:
            print(f"Error processing file {filepath}: {str(e)}")
            import traceback
            print(traceback.format_exc())
            return []
    
def process_repository(repo_path: str, output_path: str, config: Optional[Config] = None) -> None:
    """Process all C files in a repository"""
    parser = CParser(config)
    
    c_files = [
        os.path.join(root, f)
        for root, _, files in os.walk(repo_path)
        for f in files
        if f.lower().endswith(('.c', '.h'))
    ]
    
    print(f"Found {len(c_files)} C/H files to process")
    
    all_nodes = []
    from tqdm import tqdm
    with tqdm(total=len(c_files)) as pbar:
        for filepath in c_files:
            pbar.set_description(filepath)
            try:
                nodes = parser.process_file(filepath)
                print(f"Processed {len(nodes)} nodes from {filepath}")
                all_nodes.extend(nodes)
            except Exception as e:
                print(f"Error processing {filepath}: {str(e)}")
                continue
            pbar.update(1)
    # Convert nodes to dictionary for JSON serialization
    nodes_dict = []
    for node in all_nodes:
        node_dict = {
            'id': node.id,
            'text': node.text,
            'type': node.type,
            'children_types': node.children_types,
            'origin_file': node.origin_file,
            'parent_id': node.parent_id,
            'parent_type': node.parent_type,
            'relationships': node.relationships
        }
        
        if node.chunks:
            node_dict['chunks'] = [
                {
                    'id': chunk.id,
                    'text': chunk.text,
                    'type': chunk.type,
                    'children_types': chunk.children_types,
                    'origin_file': chunk.origin_file,
                    'parent_id': chunk.parent_id,
                    'relationships': chunk.relationships
                }
                for chunk in node.chunks
            ]
        else:
            node_dict['chunks'] = None
            
        nodes_dict.append(node_dict)

    with open(output_path, 'w', encoding='utf-8') as file:
        json.dump(nodes_dict, file, ensure_ascii=False, indent=4)
    print(f"Successfully wrote {len(nodes_dict)} nodes to {output_path}")


if __name__ == "__main__":
    config = Config(MAX_TOKENS=2000, TRAVERSE_DEPTH=2)
    process_repository('data/versa', 'output.json', config)