[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[program:fastapi]
command=uvicorn main:app --host 0.0.0.0 --port 80
directory=/app/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
redirect_stderr=true
environment=PYTHONUNBUFFERED="1"

[program:taskiq]
command=taskiq worker services.taskiq.broker:broker
directory=/app/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
redirect_stderr=true
environment=PYTHONUNBUFFERED="1"
