# Generated by Django 5.2.9 on 2025-12-14 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='Stores user preferences: city, budget_min, budget_max, bedrooms, property_type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_lead',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='core.lead')),
            ],
            options={
                'db_table': 'core_conversation',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata like tool calls, shortlisted projects, etc.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
            ],
            options={
                'db_table': 'core_message',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=500, null=True)),
                ('no_of_bedrooms', models.IntegerField(blank=True, null=True)),
                ('completion_status', models.CharField(blank=True, max_length=50, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('unit_type', models.CharField(blank=True, max_length=200, null=True)),
                ('developer_name', models.CharField(blank=True, max_length=300, null=True)),
                ('price_usd', models.IntegerField()),
                ('area_sq_mtrs', models.IntegerField()),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('project_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_project',
                'indexes': [models.Index(fields=['city'], name='core_projec_city_518ef0_idx'), models.Index(fields=['price_usd'], name='core_projec_price_u_63011f_idx'), models.Index(fields=['no_of_bedrooms'], name='core_projec_no_of_b_c3fd1f_idx'), models.Index(fields=['property_type'], name='core_projec_propert_f878fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the booking')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.conversation')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.lead')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.project')),
            ],
            options={
                'db_table': 'core_booking',
                'ordering': ['-booking_date'],
            },
        ),
    ]
