name: Bundle Deployment for Dev

on:
  push:
    branches:
      - 'dev' 
  pull_request:
    branches:
      - 'dev'
    types:
      - closed
  workflow_dispatch:

concurrency: integration-test-dev

jobs:
  linting:
    runs-on: ai-coding-runner  
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r ./.github/test-requirements.txt   
      - name: Check code format
        run: |
            black --check .         
      # - name: Check code format
      #   run: |
      #       flake8 .

  unit_tests:
    needs: linting
    runs-on: ai-coding-runner  
    steps:
      - name: unit_test
        run: |
            echo "Skip unit test"
      # - uses: actions/checkout@v4
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: 3.8
      # - name: Install dependencies
      #   run: |
      #       python -m pip install --upgrade pip
      #       pip install -r ./.github/test-requirements.txt
      # - name: Run tests with pytest
      #   run: |
      #       pytest

  dev:
    needs: unit_tests
    runs-on: ai-coding-runner 
    env: 
      azure-cli: 2.62.0-1~$(lsb_release -cs)
      vault: kv-ai-nonprod-dso-001
      dbx-clientid-key: coding-client-id-dev
      dbx-sc-key: coding-client-secret-dev
      dbx-pat: coding-pat-dev
    steps: 
      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg -y
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli=${{ env.azure-cli }} -y
          az --version
      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # enable-AzPSSession: true
      - name: Install Azure CLI
        run: |
          DATABRICKS_CLIENT_ID=$(az keyvault secret show --name ${{ env.dbx-clientid-key }} --vault-name ${{ env.vault }} --query value -o tsv)
          DATABRICKS_CLIENT_SECRET=$(az keyvault secret show --name ${{ env.dbx-sc-key }} --vault-name ${{ env.vault }} --query value -o tsv)
          DATABRICKS_PAT=$(az keyvault secret show --name ${{ env.dbx-pat }} --vault-name ${{ env.vault }} --query value -o tsv)
          echo "::add-mask::$DATABRICKS_PAT"
          echo DATABRICKS_PAT=$DATABRICKS_PAT >> $GITHUB_ENV
          echo "::add-mask::$DATABRICKS_CLIENT_ID"
          echo DATABRICKS_CLIENT_ID=$DATABRICKS_CLIENT_ID >> $GITHUB_ENV
          echo "::add-mask::$DATABRICKS_CLIENT_SECRET"
          echo DATABRICKS_CLIENT_SECRET=$DATABRICKS_CLIENT_SECRET >> $GITHUB_ENV
          
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check working directory
        run: |
          sudo apt update -y
          sudo apt install curl unzip -y
      - uses: databricks/setup-cli@v0.233.0
      - name: Validate Bundle on Dev Workspace
        id: validate
        run: |
          databricks bundle validate --var="dbx_token=$DATABRICKS_PAT" -t dev
      - name: Deploy Bundle on Dev Workspace
        id: deploy
        run: |
          databricks bundle deploy --var="dbx_token=$DATABRICKS_PAT" -t dev


      

